import { StyleSheet } from 'react-native';

const colors = {
  corPrimaria: '#9800ce',
  corSecundaria: '#2a2f43ea',
  corFundo: '#f5f5f5',
  corBranca: '#fff',
  corCinza: '#ddddde',
  corVermelha: '#ff4d4d',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.corBranca,
  },
  body: {
    width: '100%',
    margin: 0,
    padding: 0,
    overflow: 'hidden',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    backgroundColor: colors.corPrimaria,
    height: 80,
    justifyContent: 'space-between',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    zIndex: 999,
  },
  textoHeader: {
    fontSize: 20,
    color: colors.corBranca,
    fontFamily: 'Montserrat_700Bold',
    textAlign: 'left',
    alignSelf: 'flex-end',
    marginBottom: 5,
    marginRight: 'auto',
    paddingLeft: 15,
  },
  footer: {

  },
  imagem: {
    margin: 0,
    height: 80,
    width: 80,
  },
  icon: {
    fontSize: 25,
    color: colors.corBranca,
    marginLeft: 5,
    alignSelf: 'flex-end',
    marginTop: 'auto',
    paddingRight: 15,
    marginBottom: 5,
  },
  produtos: {
    width: '90%',
    maxWidth: 1200,
    borderRadius: 8,
    margin: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  produtosItens: {
    textAlign: 'center',
    color: colors.corPrimaria,
    marginBottom: 20,
    width: '100%',
  },
  produto: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: colors.corBranca,
    padding: 10,
    margin: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width: '100%',
    boxSizing: 'border-box',
  },
  produtoImagem: {
    width: 110,
    height: 90,
    resizeMode: 'cover',
    marginBottom: 10,
  },
  produtoNome: {
    color: colors.corPrimaria,
    fontSize: 18,
    margin: 10,
    fontWeight: '700',
  },
  produtoPreco: {
    color: colors.corSecundaria,
    fontWeight: 'bold',
    fontSize: 18,
    margin: 10,
  },
  produtoButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: colors.corPrimaria,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  produtoButtonText: {
    color: colors.corBranca,
    fontSize: 16,
    fontWeight: 'bold',
  },
  carrinho: {
    flex: 1,
    backgroundColor: colors.corBranca,
    padding: 10,
  },
  headerCarrinho: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  textoCarrinho: {
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  carrinhoItem: {
    flexDirection: 'row',
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.corCinza,
    borderRadius: 8,
  },
  quantidadeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 80,
  },
  botaoFinalizar: {
    backgroundColor: colors.corPrimaria,
    padding: 15,
    alignItems: 'center',
    borderRadius: 8,
    marginTop: 20,
  },
  textoBotaoFinalizar: {
    color: colors.corBranca,
    fontSize: 18,
    fontWeight: 'bold',
  }, 
  popup: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -150 }, { translateY: -75 }], // Centraliza o pop-up
    width: 300,
    height: 150,
    backgroundColor: '#d4edda',
    borderColor: '#c3e6cb',
    borderWidth: 1,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5, // Sombra no Android
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84, // Sombra no iOS
  },
  textoPopup: {
    color: '#155724',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },  
  carrinhoIconContainer: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end'
  },
  badge: {
    position: 'absolute',
    top: -6,
    right: 8,
    backgroundColor: colors.corVermelha,
    borderRadius: 12,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: colors.corBranca,
    fontSize: 10,
    fontWeight: 'bold',
  },  
});

export default styles;